---
- name: Enable passwordless sudo for admin user {{ admin.name }}
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ admin.name }}"
    line: "{{ admin.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: import ssh tasks
  import_tasks: ssh.yml

- name: include OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

