---
# tasks file for ruby

- name: Install basic packages
  dnf:
    name: "{{ basic_packages }}"
    state: present

- name: install additional packages
  dnf:
    name: "{{ additional_packages }}"
    state: present
  when: additional_packages is defined

- name: remove packages
  dnf:
    name: "{{ remove_packages }}"
    state: absent
  when: remove_packages is defined

- name: All packages installed.
  debug:
    msg: Packages have been successfully installed
