---
- name: print public key file name
  debug:
    msg: "{{ admin.pubkeys }}"

- name: Add SSH public key
  ansible.posix.authorized_key:
    user: "{{ admin.name }}"
    key: "{{ item }}"
  with_file:
    "{{ admin.pubkeys }}"

- name: Secure sshd config
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: /usr/sbin/sshd -T -f %s
  with_items:
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^AuthenticationMethods"
      line: "AuthenticationMethods publickey"
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
  notify:
    - restart sshd

